# todo-api-chart/templates/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-api-chart.fullname" . }}-api-deployment
  labels:
    {{- include "todo-api-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount }} # HPA will manage this if enabled
  selector:
    matchLabels:
      {{- include "todo-api-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "todo-api-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: todo-api-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: {{ include "todo-api-chart.fullname" . }}-postgres-db-service # DB service name generated by Helm
            - name: DB_PORT
              value: "{{ .Values.db.port }}"
            - name: DB_USER
              value: {{ .Values.db.user }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-credentials # <-- Hardcoded name for the external Secret
                  key: db_password
            - name: DB_NAME
              value: {{ .Values.db.name }}
          resources:
            requests:
              cpu: "100m" # Essential for HPA to work based on CPU
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"