# flask-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service # Name of the Service to expose the Flask app
spec:
  selector:
    app: flask-app # Selects Pods with the label 'app: flask-app'
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the Service (e.g., accessed via HTTP on port 80)
      targetPort: 5000 # Port on the Pods where the Flask app is listening
  type: LoadBalancer # Service type: attempts to provision an external load balancer