# 01-db-secret.yaml
apiVersion: v1
kind: Secret # Kubernetes object for storing sensitive data (e.g., passwords, API keys)
metadata:
  name: db-credentials # Name of the Secret. Referenced by the Deployment.
type: Opaque # Default type for arbitrary user-defined data.
data:
  # Data values must be base64 encoded.
  # You can generate this with: echo -n "your_password" | base64
  # For 'password', base64 is 'cGFzc3dvcmQ='
  db_password: cGFzc3dvcmQ=